spring.application.name=Transport Management System
server.port=4000
# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/tms_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Shubham@16$2000

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
